apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: demo-deploy
  name: demo-deploy
  namespace: dev-demo-ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-deploy
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: demo-deploy
    spec:
      containers:
      - image: nginx
        name: nginx
        resources: {}
status: {}
